# Generated by Django 2.1.15 on 2023-04-24 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myLibrary.myAdminValidator


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0003_remove_bloodbank_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='email',
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(max_length=254, validators=[myLibrary.myAdminValidator.AdminValidation.is_valid_email]),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[myLibrary.myAdminValidator.AdminValidation.is_valid_phone]),
        ),
    ]
