# Generated by Django 2.1.15 on 2023-04-22 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230422_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_user.Clinic'),
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
    ]
