# Generated by Django 2.1.15 on 2023-04-24 20:16

from django.db import migrations, models
import myLibrary.myMainValidator


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230422_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(validators=[myLibrary.myMainValidator.MainValidation.is_valid_age]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[myLibrary.myMainValidator.MainValidation.is_valid_phone]),
        ),
    ]
